export default ({
     "background": [
      "red conical gradient",
      "purple",
      "blue conical gradient",
      "light brown",
      "blue",
      "orange",
      "green",
      "pink",
      "light gray",
      "day landscape",
      "blue linear gradient",
      "gray",
      "red linear gradient",
      "purple conical gradient",
      "yellow",
      "orange conical gradient",
      "yellow linear gradient",
      "purple linear gradient",
      "pink linear gradient",
      "green conical gradient",
      "snow landscape",
      "night landscape"
    ],
    "body": [
      "lime green",
      "teal",
      "yellow linear gradient",
      "gray",
      "red",
      "purple",
      "blue",
      "yellow",
      "blue linear gradient",
      "pink",
      "orange linear gradient",
      "purple linear gradient",
      "pink linear gradient",
      "green",
      "aqua",
      "light green",
      "green linear gradient",
      "rainbow",
      "grayspace linear gradient"
    ],
    "chest": [
      "pink",
      "orange",
      "orangered",
      "aqua",
      "green",
      "purple",
      "light gray",
      "yellow",
      "gray",
      "light blue",
      "blue"
    ],
    "eyes": [
      "yellow",
      "white",
      "red",
      "green",
      "dark gray",
      "dark red",
      "blue",
      "purple",
      "orange",
      "blue yellow",
      "light gray",
      "green red",
      "lazer"
    ],
    "face": [
      "normal",
      "skull",
      "vizor",
      "ninja",
      "mask",
      "bandages",
      "noun glasses"
    ],
    "feet": [
      "rocket boots",
      "normal",
      "skateboard",
      "hoverboard"
    ],
    "hands": [
      "normal",
      "cast right",
      "cast left",
      "kite"
    ],
    "head": [
      "none",
      "two tone cap backwards",
      "cap forwards",
      "cap backwards",
      "chef",
      "crown",
      "long peak cap forwards",
      "headphones",
      "silly yellow",
      "bandana",
      "mouse ears"
    ],
    "spikes": [
      "burnt orange",
      "yellow",
      "green",
      "light gray",
      "purple",
      "blue",
      "red",
      "pink",
      "white",
      "dark gray",
      "multicolor",
      "orange",
      "teal",
      "none"
    ],
    "1/1": [
      "opt",
      "ftm",
      "rexx",
      "poly",
      "friendly dino",
      "ghost",
      "arb",
      "smol birb",
      "xoshi",
      "bsc",
      "avax",
      "mfer",
      "rapter",
      "eth",
      "cryptoad"
    ]
  })